### ISSUE TITLE
无法正常使用 2022-blake3

### ISSUE THREAD

**Issue by loveqianool** [SagerNet/v2ray-core#15]
两端都是 5.0.16
配置按照 https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022
长度十六三二都试过，不管使用 2022 哪种加密方法，均会报以下错误。
`proxy/shadowsocks: failed to read response header > cipher: message authentication failed`

**Comment by nekohasekai** [comment]
由于 *ray 性能原因，SN core 没有实现服务器。
